import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';
import { CONTENT_TYPES } from './config/navigation';

function normalizedTagSlug(tag: string): string {
  return (
    tag
      .trim()
      .toLowerCase()
      .replace(/[\s_]+/g, '-')
      .replace(/[^a-z0-9-]/g, '') || tag.trim()
  );
}

/**
 * Wiki content collection.
 *
 * Articles live at src/content/wiki/<locale>/<contentType>/<slug>.mdx
 * The `id` generated by the glob loader is the path relative to base, without extension,
 * e.g. "en/bosses/emberfang".
 *
 * Frontmatter is validated at build time by the Zod schema below. A missing or
 * malformed field fails the build immediately.
 *
 * `image` uses the `image()` helper so covers are processed by Astro Image
 * (auto WebP/AVIF + responsive srcset). Frontmatter value is a path relative
 * to the MDX file, e.g. `image: '../../../assets/covers/emberfang-cover.svg'`.
 * At build time `entry.data.image` is `ImageMetadata | undefined`. For an
 * absolute og:image URL, read `.src` and prefix with `siteUrl`.
 */
const wiki = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/wiki' }),
  schema: ({ image }) =>
    z.object({
      title: z.string().max(80),
      /** Optional shorter search/social title; visible H1 remains `title`. */
      seoTitle: z.string().max(65).optional(),
      description: z.string().min(40).max(165),
      /**
       * Hard gate: the category MUST be a NAVIGATION_CONFIG key. A typo'd
       * category would otherwise build a soft-404 page that sitemap/RSS/
       * llms.txt still publish — the enum fails the build instead.
       */
      category: z.enum(CONTENT_TYPES as [string, ...string[]]),
      date: z.coerce.date(),
      lastModified: z.coerce.date().optional(),
      image: image().optional(),
      /** Alternative text for the social/cover image. Falls back to the article title. */
      imageAlt: z.string().min(1).max(200).optional(),
      tags: z
        .array(z.string().trim().min(1, 'tag must not be blank'))
        .superRefine((tags, context) => {
          const seen = new Map<string, number>();
          tags.forEach((tag, index) => {
            const slug = normalizedTagSlug(tag);
            const previous = seen.get(slug);
            if (previous !== undefined) {
              context.addIssue({
                code: z.ZodIssueCode.custom,
                path: [index],
                message: `tag resolves to the same URL slug as tags[${previous}] (${slug})`,
              });
            } else {
              seen.set(slug, index);
            }
          });
        })
        .default([]),
      noindex: z.boolean().default(false),
      /**
       * Draft articles: visible in `pnpm dev`, excluded from the production
       * build (pages, lists, recent, related, hreflang, sitemap).
       */
      draft: z.boolean().default(false),
      /**
       * Game version this article applies to (e.g. "v2.5"). Rendered as a
       * badge on the article header — a freshness/E-E-A-T signal for
       * fast-patching games. Optional.
       */
      gameVersion: z.string().max(20).optional(),
      /** Per-article review window; overrides the category policy in config/seo.ts. */
      refreshAfterDays: z.number().int().min(1).max(365).optional(),
      /**
       * Quick-answer summary shown before the article body (AI Overviews /
       * featured snippet). Authoring rule: 40–60 words. English at that
       * length runs ~250–350 chars, so the cap is 400 — the old 200-char cap
       * contradicted the word rule (40 English words ≈ 230+ chars) and
       * silently forced every compliant summary underweight.
       */
      summary: z.string().max(400).optional(),
      /** Article author name (E-E-A-T signal). Falls back to site.defaultAuthor. */
      author: z.string().optional(),
      /**
       * Optional evidence record for source-sensitive pages. When present it
       * is rendered as a visible verification panel and its URLs are emitted
       * as Article JSON-LD citations. Keeping the evidence beside the claim
       * makes fast-changing game facts auditable without forcing every legacy
       * article to migrate at once.
       */
      evidence: z
        .object({
          status: z.enum(['official', 'verified', 'mixed', 'community', 'unconfirmed']),
          checkedAt: z.coerce.date(),
          sources: z
            .array(
              z.object({
                label: z.string().min(1).max(100),
                url: z
                  .string()
                  .url()
                  .refine((value) => /^https?:\/\//i.test(value), {
                    message: 'evidence source URL must use http or https',
                  }),
                kind: z
                  .enum(['official', 'primary', 'secondary', 'community'])
                  .default('secondary'),
              }),
            )
            .min(1)
            .max(12),
        })
        .optional(),
      /**
       * Optional structured boss stats — rendered as a scannable data card
       * (BossStatCard) above the article body. Values are strings so authors
       * can express nuance ("4200 (Phase 2: 6300)").
       */
      boss: z
        .object({
          hp: z.string(),
          weakness: z.string(),
          resistant: z.string(),
          location: z.string(),
          recommendedLevel: z.string().optional(),
        })
        .optional(),
      /**
       * Optional related YouTube videos. A bare ID keeps the legacy lazy
       * embed but deliberately emits no VideoObject: the video's real upload
       * date cannot be inferred from the article date. Use the structured
       * form when truthful metadata is available.
       */
      videos: z
        .array(
          z.union([
            z.string().regex(/^[A-Za-z0-9_-]{11}$/),
            z.object({
              id: z.string().regex(/^[A-Za-z0-9_-]{11}$/),
              title: z.string().min(1).max(120),
              description: z.string().min(20).max(300),
              uploadDate: z.coerce.date(),
            }),
          ]),
        )
        .optional(),
      /**
       * Optional image gallery — rendered as a thumbnail grid below the
       * article body with a native <dialog> lightbox (zero JS until click).
       * `image` is a path relative to the MDX file (same as the cover);
       * demo convention: gallery art lives in `src/assets/gallery/`,
       * covers in `src/assets/covers/`.
       */
      gallery: z
        .array(
          z.object({
            image: image(),
            caption: z.string().max(200).optional(),
            alt: z.string().max(200).optional(),
          }),
        )
        .default([]),
      /**
       * Structured redeem codes (codes pages). Rendered as a CodesTable
       * above the article body: Active section (CodeBlock, one-click copy)
       * + Expired section (table, long-tail SEO for "is X still working").
       * `status` drives the split; `expiryDate`/`source` are freshness and
       * E-E-A-T signals. Body stays for prose (how to redeem, reward notes).
       */
      codes: z
        .array(
          z.object({
            code: z.string().min(1),
            reward: z.string().optional(),
            status: z.enum(['active', 'expired']).default('active'),
            expiryDate: z.string().max(40).optional(),
            source: z.string().optional(),
          }),
        )
        .optional(),
    }),
});

/**
 * Handbook collection — the in-site documentation center at /landing/docs
 * (+ /zh/landing/docs). Chapters live OUTSIDE src/content on purpose: the
 * markdown under docs/handbook/ is the single source of truth, browsable on
 * GitHub, and **survives `pnpm apply-template`** (the learning manual's SOPs
 * and AI prompts are directly useful to fork users) — only the landing ROUTES
 * are removed by the CLI.
 *
 * Files: docs/handbook/<locale>/<slug>.md → id "en/<slug>" / "zh/<slug>".
 * zh chapters MUST reuse the same ASCII slug as their en counterpart —
 * CJK filenames percent-encode in URLs, and 1:1 slug pairing makes the
 * en/zh parity test (tests/handbook.test.ts) trivial.
 *
 * Plain .md (not .mdx): handbooks are static prose + code blocks; they do not
 * use the wiki component vocabulary.
 */
const handbook = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './docs/handbook' }),
  schema: z.object({
    title: z.string().max(80),
    description: z.string().min(40).max(165),
    /** Which manual the chapter belongs to (drives hub grouping + prev/next scope). */
    manual: z.enum(['learn', 'dev']),
    /** Position within the manual (1-based, unique per manual). */
    order: z.number().int(),
    icon: z.string().default('lucide:book-open'),
    /**
     * 40–60 word direct answer, rendered as the TL;DR card (AI Overviews
     * candidate). 480 chars ≈ 60-70 English words — zh lands well under,
     * en translations run longer per word.
     */
    tldr: z.string().max(480).optional(),
    /** Last content review — feeds the sitemap lastmod scan (astro.config.ts). */
    updated: z.coerce.date().optional(),
  }),
});

export const collections = { wiki, handbook };
